### ISSUE TITLE
Replace fastgit.org with github

### ISSUE THREAD

**Issue by geeks121** [jdhao/nvim-config#36] opened 2021-12-26 11:56 UTC
The current PackerSync url give the error failed to install ,, and i check the repot with hub.fastgit.org/ to github url and it works,,

**Comment by jdhao** [comment] 2021-12-26 12:25
This is a duplicate of https://github.com/jdhao/nvim-config/issues/24#issuecomment-962963035.

**Comment by jdhao** [comment] 2021-12-26 12:26
You can change this config to fit your needs. There is no need to strictly adhere to this config. Do whatever works for you or take whatever you find useful.

**Closed by jdhao** 2021-12-26 12:26 UTC

**Comment by jdhao** [comment] 2022-02-08 05:14
fastgit removed in https://github.com/jdhao/nvim-config/commit/15dfccf81ee7e78836d4f65f9a81eb400b0f1b08.
